// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth-form-label': string;
  'authFormLabel': string;
  'cancel-button': string;
  'cancelButton': string;
  'drawLine': string;
  'loader': string;
  'pencilRot': string;
}
export const cssExports: CssExports;
export default cssExports;
