// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'cancel-button': string;
  'cancelButton': string;
  'image': string;
  'image-container': string;
  'imageContainer': string;
  'input': string;
  'modal': string;
  'preview-title': string;
  'previewTitle': string;
  'save-button': string;
  'saveButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
