// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron-button': string;
  'chevronButton': string;
}
export const cssExports: CssExports;
export default cssExports;
