// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'currency': string;
  'form': string;
  'input': string;
  'label': string;
  'max-price-container': string;
  'maxPriceContainer': string;
  'min-price-container': string;
  'minPriceContainer': string;
  'price-input': string;
  'price-inputs-container': string;
  'priceInput': string;
  'priceInputsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
