// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image': string;
  'link': string;
  'location': string;
  'name': string;
  'result': string;
  'subjects': string;
}
export const cssExports: CssExports;
export default cssExports;
