// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'date': string;
  'image': string;
  'name': string;
  'review-container': string;
  'reviewContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
