// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron-container': string;
  'chevronContainer': string;
  'container': string;
  'content': string;
  'description-container': string;
  'descriptionContainer': string;
  'image-container': string;
  'imageContainer': string;
  'title': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
