// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'cancel-button': string;
  'cancelButton': string;
  'edit-title': string;
  'editTitle': string;
  'form': string;
  'form-city': string;
  'form-content': string;
  'form-info-container': string;
  'formCity': string;
  'formContent': string;
  'formInfoContainer': string;
  'image-container': string;
  'imageContainer': string;
  'input': string;
  'label': string;
  'save-button': string;
  'saveButton': string;
}
export const cssExports: CssExports;
export default cssExports;
