// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-button-container': string;
  'actionButtonContainer': string;
  'approve-button': string;
  'approveButton': string;
  'deny-button': string;
  'denyButton': string;
  'info': string;
  'info-container': string;
  'infoContainer': string;
  'message-button': string;
  'messageButton': string;
  'name': string;
  'subject': string;
}
export const cssExports: CssExports;
export default cssExports;
