// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'cancel-button': string;
  'cancelButton': string;
  'message': string;
  'modal': string;
}
export const cssExports: CssExports;
export default cssExports;
