// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth-navlink': string;
  'authNavlink': string;
  'header': string;
  'nav-link': string;
  'nav-toggle': string;
  'navLink': string;
  'navToggle': string;
  'portal-title': string;
  'portalTitle': string;
  'sign-out-button': string;
  'signOutButton': string;
}
export const cssExports: CssExports;
export default cssExports;
