// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'details-container': string;
  'detailsContainer': string;
  'info-container': string;
  'infoContainer': string;
  'name': string;
  'page-container': string;
  'pageContainer': string;
  'reviews-container': string;
  'reviewsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
