// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'list': string;
  'loader-container': string;
  'loaderContainer': string;
  'no-results-message': string;
  'noResultsMessage': string;
  'top-level': string;
  'topLevel': string;
}
export const cssExports: CssExports;
export default cssExports;
