// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'info': string;
}
export const cssExports: CssExports;
export default cssExports;
