// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron-button': string;
  'chevronButton': string;
  'content': string;
  'files-container': string;
  'filesContainer': string;
  'hr': string;
  'link-list': string;
  'linkList': string;
  'no-content': string;
  'noContent': string;
  'section': string;
  'section-title': string;
  'sectionTitle': string;
  'subtitle': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
