// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'banner-container': string;
  'bannerContainer': string;
  'image': string;
  'image-container': string;
  'imageContainer': string;
  'subtitle': string;
  'title': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
