// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancel-button': string;
  'cancelButton': string;
  'delete-button': string;
  'deleteButton': string;
  'modal-content': string;
  'modalContent': string;
}
export const cssExports: CssExports;
export default cssExports;
