// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'form': string;
  'input': string;
  'step-display': string;
  'stepDisplay': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
