// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'card': string;
  'form': string;
  'next-button': string;
  'nextButton': string;
  'step-display': string;
  'stepDisplay': string;
}
export const cssExports: CssExports;
export default cssExports;
