// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'dropdown': string;
  'dropdown-name': string;
  'dropdownName': string;
  'form': string;
  'input': string;
  'select': string;
  'subject-input': string;
  'subjectInput': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
