// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'currency': string;
  'input': string;
  'price-input-container': string;
  'price-inputs': string;
  'price-label': string;
  'priceInputContainer': string;
  'priceInputs': string;
  'priceLabel': string;
  'remove-button': string;
  'removeButton': string;
  'subject-title': string;
  'subjectTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
