// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'input': string;
  'remove-button': string;
  'removeButton': string;
}
export const cssExports: CssExports;
export default cssExports;
