// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'link-container': string;
  'linkContainer': string;
  'popup-button': string;
  'popupButton': string;
}
export const cssExports: CssExports;
export default cssExports;
