// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nav-link': string;
  'navLink': string;
}
export const cssExports: CssExports;
export default cssExports;
