// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'container': string;
  'header': string;
  'image': string;
  'name': string;
  'recipient-info': string;
  'recipientInfo': string;
  'window': string;
}
export const cssExports: CssExports;
export default cssExports;
