export type CloudinaryUploadResponse = {
  asset_id: string,
  public_id: string,
  version: number,
  version_id: string,
  signature: string | null | undefined,
  width: number,
  height: number,
  format: string,
  resource_type: string,
  created_at: string,
  tags?: string[],
  pages?: number,
  bytes: number,
  type: string,
  etag?: string,
  placeholder: boolean,
  url: string,
  secure_url: string,
  access_mode: string,
  original_filename?: string,
  eager?: any,
  media_metadata: any
}