// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form-container': string;
  'formContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
