// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'button-container': string;
  'buttonContainer': string;
  'modal': string;
  'remove-button': string;
  'removeButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
