// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'file-container': string;
  'file-name': string;
  'fileContainer': string;
  'fileName': string;
  'image': string;
  'image-container': string;
  'imageContainer': string;
  'popover-button-container': string;
  'popover-option': string;
  'popoverButtonContainer': string;
  'popoverOption': string;
}
export const cssExports: CssExports;
export default cssExports;
