// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls-container': string;
  'controlsContainer': string;
  'title': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
