// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'empty-subtitle': string;
  'emptySubtitle': string;
  'first-button': string;
  'first-button-container': string;
  'firstButton': string;
  'firstButtonContainer': string;
  'title': string;
  'upload-button': string;
  'upload-button-container': string;
  'uploadButton': string;
  'uploadButtonContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
