// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'cancel-button': string;
  'cancelButton': string;
  'input': string;
  'update-button': string;
  'updateButton': string;
}
export const cssExports: CssExports;
export default cssExports;
