// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'buttonContainer': string;
  'cancel-button': string;
  'cancelButton': string;
  'input': string;
  'modal': string;
  'review-button': string;
  'reviewButton': string;
  'select': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
