// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details-container': string;
  'detailsContainer': string;
  'edit-button': string;
  'editButton': string;
  'image-container': string;
  'image-edit-button': string;
  'imageContainer': string;
  'imageEditButton': string;
  'info-container': string;
  'infoContainer': string;
  'location': string;
  'name': string;
  'page-container': string;
  'pageContainer': string;
  'profile-container': string;
  'profileContainer': string;
  'subjects-container': string;
  'subjectsContainer': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
