// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'form': string;
  'input': string;
  'upload-button': string;
  'uploadButton': string;
}
export const cssExports: CssExports;
export default cssExports;
