// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'cancel-button': string;
  'cancelButton': string;
  'message': string;
  'modal': string;
  'select': string;
  'send-button': string;
  'sendButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
