// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal-title': string;
  'modalTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
