// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty-subtitle': string;
  'emptySubtitle': string;
  'search-button': string;
  'search-button-container': string;
  'searchButton': string;
  'searchButtonContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
