// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link': string;
  'link-container': string;
  'linkContainer': string;
  'links-container': string;
  'linksContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
