// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'input': string;
  'radius-display': string;
  'radiusDisplay': string;
}
export const cssExports: CssExports;
export default cssExports;
