// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron-button': string;
  'chevronButton': string;
  'content': string;
  'file-image': string;
  'file-image-container': string;
  'fileImage': string;
  'fileImageContainer': string;
  'files-container': string;
  'filesContainer': string;
  'hr': string;
  'no-content': string;
  'noContent': string;
  'section': string;
  'subtitle': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
