// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'chevron-button': string;
  'chevronButton': string;
  'content': string;
  'file-container': string;
  'file-image': string;
  'file-image-container': string;
  'file-name': string;
  'fileContainer': string;
  'fileImage': string;
  'fileImageContainer': string;
  'fileName': string;
  'files-container': string;
  'filesContainer': string;
  'hr': string;
  'link-container': string;
  'linkContainer': string;
  'message-button': string;
  'messageButton': string;
  'name': string;
  'no-content': string;
  'noContent': string;
  'profile-button': string;
  'profileButton': string;
  'right': string;
  'section': string;
  'subtitle': string;
  'title-container': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
