// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'currency': string;
  'edit-button': string;
  'editButton': string;
  'input': string;
  'max-price-container': string;
  'maxPriceContainer': string;
  'price-container': string;
  'price-inputs-container': string;
  'priceContainer': string;
  'priceInputsContainer': string;
  'save-button': string;
  'saveButton': string;
  'subtitle': string;
}
export const cssExports: CssExports;
export default cssExports;
