// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-button': string;
  'addButton': string;
  'container': string;
  'form': string;
  'next-button': string;
  'next-button-container': string;
  'nextButton': string;
  'nextButtonContainer': string;
  'step-display': string;
  'stepDisplay': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
