name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: npm ci --dev
      - run: npm ci
      - run: npm run lint
      - name: test
        run: |
          npm run setup-db
          npm run test -- --runInBand
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
        env:
          CI: true
          DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}