// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttonContainer': string;
  'container': string;
  'edit-image-button': string;
  'edit-name-button': string;
  'editImageButton': string;
  'editNameButton': string;
  'image-container': string;
  'imageContainer': string;
  'input': string;
  'label': string;
  'name': string;
  'name-container': string;
  'nameContainer': string;
  'save-button': string;
  'saveButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
